name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  macos-build-release:
    runs-on: macOS-11
    strategy:
      matrix:
        xcode: ["11.7", "12.5.1", "13.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      
      - name: Build Release
        run: make buildRelease
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

      - name: Build SimctlCLI Release
        run: make buildSimctlCLI
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

      - name: Upload build artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v2.3.1
        with:
          name: build-artifacts-${{ matrix.xcode }}-${{ github.run_id }}
          path: |
            *.lcov
            .build/*.yaml
            .build/**/*.a
            .build/**/*.so
            .build/**/*.dylib
            .build/**/*.dSYM 
            .build/**/*.json
