name: pod-lib-lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  pod-lib-lint:
    runs-on: macOS-11
    strategy:
      matrix:
        xcode: ["13.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app

      - name: Pod lib lint
        run: |
          bundle install
          make podLibLint
        env:
            DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
